trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Initializing Terraform..."
    terraform init -backend-config="storage_account_name=tfstateuvqbm" -backend-config="container_name=tfstate" -backend-config="access_key=$(StorageAccountAccessKey)" -backend-config="key=terraform.tfstate"
  displayName: 'Terraform Init'

- script: |
    echo "Validating Terraform files..."
    terraform validate
  displayName: 'Terraform Validate'

- script: |
    echo "Applying Terraform..."
    terraform apply -auto-approve
  env:
    ARM_SUBSCRIPTION_ID: $(subscription_id)
    ARM_CLIENT_ID: $(client_id)
    ARM_CLIENT_SECRET: $(client_secret)
    ARM_TENANT_ID: $(tenant_id)
  displayName: 'Terraform Apply'
